### ISSUE TITLE
Multiblock plushables

### ISSUE THREAD

**Issue by DWX12** [Khazoda/Plushables#3]
I think it would be cool if you were to add in plushies of Minecraft mobs and bosses. A number of them already exist and can be purchased so maybe they can be used as references or continue with your style.

A side note: For future interactions with plushies, maybe a simple right click event could change the color or, for example, a villager profession or a sheep's color.

Maybe a further feature is that they could negate fall damage or have similar properties to that of slime blocks.

Thank you again for this cool mod.

**Comment by DWX12** [comment]
An added idea, if you are capable of making multi-block structures, would be to add in a cluster of plushies that would transform into a larger version or a different one. For example, if you were to put together, say, a 3x2x3 of endermen plushies or a 3x2x structure of black wool with a dragon's head attached to it, the structured would transform into a large end dragon plushie. Or placing three wither skeleton plushies together could make a large wither plushie.

Just throwing some ideas out there. Again, thanks for the neat mod and taking a look at my suggestion.

**Comment by khazoda** [comment]
I know it's been a long, long time since this suggestion, but it's still valid.

For the first suggestion - vanilla mob/animal plushies, funnily a whole new mod has been made since your suggestion:
[Plushie Mod](https://github.com/Link4real/Plushie-Mod)
This mod adds many vanilla plushies, and is very faithful to the vanilla game's models and textures. As this "niche" has now been filled by the Plushie mod, I'm not planning on including vanilla mobs directly. This doesn't mean that Plushables won't have plushies that draw inspiration from vanilla mobs.

For the second idea, it's definitely something I'd like to look into, perhaps further down the line multiblock plushables could be a thing, but for now I'm putting it in the potential features section.

Thank you for your suggestions, and sorry I didn't look at them sooner 😅
